@startuml
title Nimbus 云盘客户端主要流程活动图

start

:启动客户端（初始化界面和控件）;
:显示主窗口;

while (用户操作)
  if (点击“选择文件”) then (是)
    :弹出文件选择对话框;
    :显示选中文件路径;
  elseif (点击“上传”) then (是)
    :读取文件;
    if (大文件?) then (是)
      :分片上传;
    else
      :直接上传;
    endif
    :显示上传进度;
    :上传完成提示;
    :刷新空间进度条;
  elseif (点击“下载”) then (是)
    :输入或选择文件名;
    :发送下载请求;
    :保存文件;
    :显示下载进度;
    :下载完成提示;
  elseif (点击“云端文件”) then (是)
    :请求文件列表;
    :显示文件列表;
  elseif (点击“回收站”) then (是)
    :请求回收站文件列表;
    :显示回收站文件;
  elseif (右键文件列表) then (是)
    :弹出菜单（下载/查看/重命名/删除等）;
    :执行相应操作;
    if (删除/还原/彻底删除) then (是)
      :刷新空间进度条;
    endif
  elseif (点击“登出”) then (是)
    :发送登出请求;
    :清空界面;
    :弹出登录窗口;
    if (登录成功) then (是)
      :保存新 token;
      :刷新空间进度条;
    else
      :退出程序;
    endif
  endif
endwhile

stop
@enduml